### ISSUE TITLE
wifi or wired interconnect protocol parser

### ISSUE THREAD

**Issue by ebo** [debsahu/Internet_Fire_Alarm#1]
From the details I cannot tell if this just reads WiFi messages from the interconnected device, or if it can parse the data from the wired connection.  Could you clarify that?

I am looking at mashing up a couple of different code bases to:

a) connect the interconnected smoke/CO alarms with the security system, and 
b) send all security events (like open/close doors) via MQTT

**Comment by debsahu** [comment]
It taps into 3.3V signal that goes into alarm speaker. If the speaker beeps, alarm is sent via MQTT. This design does not tap into interconnect signals.

**Comment by ebo** [comment]
Thank you.  I will probably try to make something which reads the 
5-9vdc signal line and decode it -- apparently the newer ones 
communicate their ID, status, and trip settings.  I will let you know if 
I end up basing any of my projects off of your work as attribute, etc.
